### PR TITLE
Pass More Information in JWT Token Payload

### LINKED ISSUE #3: JWT Token Should Contain More Information from Client
JWT token should contain more information from client:

## Fields to include
* `aud` - Audience (https://tools.ietf.org/html/rfc7519#section-4.1.3)
* `jti` - JWT ID (https://tools.ietf.org/html/rfc7519#section-4.1.7)
* `consumerid` - Consumer ID (Custom)
* `consumername` - Consumer Username(Custom)

### Other fields to also consider
* `iss` - Issuer (https://tools.ietf.org/html/rfc7519#section-4.1.1)
* `iat` - Issued at (https://tools.ietf.org/html/rfc7519#section-4.1.6)

### PR DESCRIPTION
**Pull request by brianwyka**
# Fields added to JWT Token Payload
- `aud`: Kong Service Name
- `iss`: `nginx.conf` kong variable
- `iat`: current time
- `jti`: UUID
- `consumername`: Consumer Username
- `consumerid`: Consumer ID

## Other Changes
- Updated `README.md` to document usage of new claims
- Updated `README.md` to visualize JWT token contents

Closes #3

### CODE REVIEW

**Comment by brianwyka** [comment]
@rsbrisci this is still a WIP as I have some `TODO` comments in `access.lua`

**Review by rsbrisci — CHANGES_REQUESTED** [review]
From our other plugin https://github.com/Optum/kong-splunk-log/blob/master/src/basic.lua#L10
The way to get consumer data is like this:

```
ngx.ctx.authenticated_consumer.username
ngx.ctx.authenticated_consumer.id
```

Additionally, in https://github.com/Optum/kong-upstream-jwt/blob/master/src/handler.lua ; you'll need to change the plugin priority to something <1000, so it runs AFTER the auth plugins - and we know who the consumer is.

Also, I'd like to see some `nil pointer` protection, because in certain auth flows like OIDC, there is no authorized consumer present.

**Comment by brianwyka** [comment]
@rsbrisci made the changes

**Comment by jeremyjpj0916** [comment]
We should probably leverage the kong lua api as oppsosed to ngx.ctx as a standard going forward, just a thought(they intend to maintain compatibility at the api layer for consistency):
https://docs.konghq.com/1.1.x/pdk/kong.client/#kongclientget_consumer

Also if we are going to do this, we may as well add the jti claim as per RFC for replay attacks:
https://tools.ietf.org/html/rfc7519#section-4.1.7

Example of a Kong core dev playing with our plugin doing so here(they may have moved that tools lib around or part of pdk so we may need to look where that is currently in kong):
https://github.com/rainest/kong-upstream-jwt/blob/release/kong/plugins/kong-upstream-jwt/access.lua#L59

Also idk how I feel about the: 

local jwt_issuer =  os.getenv("KONG_JWT_ISSUER")
local jwt_audience =  os.getenv("KONG_JWT_AUDIENCE")

These should likely be added to the plugin schema as optional string types with default being nil for backwards compatibility, realistically the path to the cert should have been done that way as well from config not env variable. Only time env variables bring value are when we run multi dc and each "node" env variable gets set to something local to the dc, anything multi dc kong nodes can share safely should be set at conf level. 

Really wish we had come up with a solution for gateway -> api provider that does not need to read the request body into memory and sha but I don't think there is enough confidence in the security of it without that payload hash validation for xml/json body requests. Thinking on it some more we could have gotten away with it by not signing our JWTs with our certs but something outside of optum cert management/rotation policy, our own Kong public and private keys that we will just not rotate but will be kept safe. Then people don't need to read an x5c and can just keep the public key stored in their local app for the lifetime they leverage the gateway... #regrets . Also exposing the pub key on an endpoint could work but then apps have to write logic to pull it when they fail to validate, woulda added some extra complication though I don't want to support, but the first idea is ideal. 

Otherwise I do like seeing people playing with the codebase, nice first go at it!

**Comment by brianwyka** [comment]
@rsbrisci @jeremyjpj0916 made additional changes

**Comment by brianwyka** [comment]
How do you guys test this?

**Comment by rsbrisci** [comment]
@brianwyka we'll build it in dev to initially test the functionality, and if it looks good we push to stage for realistic user-senario tests.

**Comment by brianwyka** [comment]
Thanks @rsbrisci

**Comment by jeremyjpj0916** [comment]
Starting to look pretty good to me, we can review this src and test in dev likely by end of week or early next week. 

The other fun part will be updating the docs over here: 
https://docs.konghq.com/hub/optum/kong-upstream-jwt/

**Comment by brianwyka** [comment]
@jeremyjpj0916 I am assuming the doc update is after a successful release here, correct?

**Comment by jeremyjpj0916** [comment]
Correct, that will be a totally separate effort after publishing these changes to production. We need to take a little to consider this from existing API provider perspective to ensure these additions won't cause any breaking changes for api providers as well. In theory it should break no one, but I have seen people do funky stuff before 😁 .

**Comment by brianwyka** [comment]
@jeremyjpj0916 is the `iss` payload field potentially going to be overwritten by another plugin?

**Comment by rsbrisci** [comment]
@brianwyka  this is an RS256 JWT, `iss` is not used. Not sure what the purpose would be, since you're taking it from a static config in this PR.

Since the value of `iss` will always be the same, what value does this add to the flow? We need to be very conscious of size, considering this is going in an HTTP header.

**Comment by brianwyka** [comment]
@rsbrisci the thought was to use the `iss` field as an extra layer of security which can be used in the validation of the token.

`iss` is static in the context of each kong instance.  If you are not seeing it as useful, we can remove.

**Comment by jeremyjpj0916** [comment]
The issuer is a standard field in JWT for sure, but I don't see large security value presenting it in the claims. It will be dynamic coming from the configs because every gateway should set a different issuer. Setting it to things like "GatewayCoreProd" or "GatewayDMZProd" are all ways to leverage it, but its just adding more bytes to the jwt with no security gain. I see no harm in keeping it in the conf as a field that defaults to nil. There is some "standardization" value in setting those to identify each of our gateways. An attacker can still set his iss to such a value but makes sense to allow it at least. 

If we wanted to get really fancy about how we set this field, we could set it to the gateway's proxy URL path so its unique per proxy route from the lua but I think a static global is fine here.

**Comment by jeremyjpj0916** [comment]
@brianwyka Refer to here and make some reverts back to the way it was in some locations:

https://github.com/Kong/kong/issues/3424

Specifically Thibault's comment:
```
BTW, better avoid calling such non JIT-able functions like os.getenv in hot-code paths and cache them somewhere instead (like the top-level chunk of your Lua module for example).
```

So for perf reasons its better to keep the old way of local lua variables and not do os.getenv in a hotpath.

**Comment by jeremyjpj0916** [comment]
@brianwyka I think the audience field should be set to the Kong service name(which is unique) in lua(which is representative of the human readable name of the api the JWT will proxy to) and not as a conf field(because this plugin is a global for us so it has no value if set at a global level). Ex to get the service name in question do like this, as it best represents the dynamic audience(where the proxy will route):

```
  if ngx.ctx.service ~= nil then
        serviceName = ngx.ctx.service.name
  end
```

Also better yet if the Kong pdk exposes it we should do something like so if possible(have not validated if this works yet). 
```
  if kong.service ~= nil then
        serviceName = kong.service.name
  end
```

Be sure to remove it from the schema as well. 

Also you have required set to true on all newer fields defined in schema, this should be set to false as its a breaking change since this plugin never required such fields in the past(and should not need to anyways to be applied to a kong node).

```
-- © Optum 2018

return {
  fields = {
    issuer = { type = "string", required = false, default = nil },
    private_key_location = { type = "string", required = false, default = nil },
    public_key_location = { type = "string", required = false, default = nil }
  }
}
```

**Comment by brianwyka** [comment]
@jeremyjpj0916 let me know how things look, made the changes.

**Comment by jeremyjpj0916** [comment]
@brianwyka tested it successfully, here is a cleaned up access phase:
```
-- © Optum 2018
local resty_sha256 = require "resty.sha256"
local str = require "resty.string"
local singletons = require "kong.singletons"
local pl_file = require "pl.file"
local json = require "cjson"
local openssl_digest = require "openssl.digest"
local openssl_pkey = require "openssl.pkey"
local table_concat = table.concat
local encode_base64 = ngx.encode_base64
local env_private_key_location = os.getenv("KONG_SSL_CERT_KEY")
local env_public_key_location = os.getenv("KONG_SSL_CERT_DER")
local utils = require "kong.tools.utils"
local _M = {}

--- Get the private key location either from the environment or from configuration
-- @param conf the kong configuration
-- @return the private key location
local function get_private_key_location(conf)
  if env_private_key_location then
    return env_private_key_location
  end
  return conf.private_key_location
end

--- Get the public key location either from the environment or from configuration
-- @param conf the kong configuration
-- @return the public key location
local function get_public_key_location(conf)
  if env_public_key_location then
    return env_public_key_location
  end
  return conf.public_key_location
end

--- base 64 encoding
-- @param input String to base64 encode
-- @return Base64 encoded string
local function b64_encode(input)
  local result = encode_base64(input)
  result = result:gsub("+", "-"):gsub("/", "_"):gsub("=", "")
  return result
end

--- Read contents of file from given location
-- @param file_location the file location
-- @return the file contents
local function read_from_file(file_location)
  local content, err = pl_file.read(file_location)
  if not content then
    ngx.log(ngx.ERR, "Could not read file contents", err)
    return nil, err
  end
  return content
end

--- Get the Kong key either from cache or the given `location`
-- @param key the cache key to lookup first
-- @param location the location of the key file
-- @return the key contents
local function get_kong_key(key, location)
  -- This will add a non expiring TTL on this cached value
  -- https://github.com/thibaultcha/lua-resty-mlcache/blob/master/README.md
  local pkey, err = singletons.cache:get(key, { ttl = 0 }, read_from_file, location)
	
  if err then
    ngx.log(ngx.ERR, "Could not retrieve pkey: ", err)
    return
  end
	
  return pkey
end

--- Base64 encode the JWT token
-- @param payload the payload of the token
-- @param key the key to sign the token with
-- @return the encoded JWT token
local function encode_jwt_token(conf, payload, key)
  local header = {
    typ = "JWT",
    alg = "RS256",
    x5c = {
      b64_encode(get_kong_key("pubder", get_public_key_location(conf)))
    }
  }
  local segments = {
    b64_encode(json.encode(header)),
    b64_encode(json.encode(payload))
  }
  local signing_input = table_concat(segments, ".")
  local signature = openssl_pkey.new(key):sign(openssl_digest.new("sha256"):update(signing_input))
  segments[#segments+1] = b64_encode(signature)
  return table_concat(segments, ".")
end

--- Build the JWT token payload based off the `payload_hash`
-- @param conf the configuration
-- @param payload_hash the payload hash
-- @return the JWT payload (table)
local function build_jwt_payload(conf, payload_hash)
  local current_time = ngx.time() -- Much better performance improvement over os.time()
  local payload = {
    exp = current_time + 60,
    jti = utils.uuid(),
    payloadhash = payload_hash
  }

  if conf.issuer then
    payload.iat = current_time
    payload.iss = conf.issuer
  end
	
  if ngx.ctx.service then
    payload.aud = ngx.ctx.service.name
  end

  local consumer = kong.client.get_consumer()
  if consumer then
    payload.sub = consumer.id
    payload.username = consumer.username
  end

  return payload
end

--- Build the payload hash
-- @return SHA-256 hash of the request body data
local function build_payload_hash()
  ngx.req.read_body()
  local req_body  = ngx.req.get_body_data()
  local payload_digest = ""
  if req_body then
    local sha256 = resty_sha256:new()
    sha256:update(req_body)
    payload_digest = sha256:final()
  end
  return str.to_hex(payload_digest)
end

--- Add the JWT header to the reqeust
-- @param conf the configuration
local function add_jwt_header(conf)
  local payload_hash = build_payload_hash()
  local payload = build_jwt_payload(conf, payload_hash)
  local kong_private_key = get_kong_key("pkey", get_private_key_location(conf))
  local jwt = encode_jwt_token(conf, payload, kong_private_key)
  ngx.req.set_header("JWT", jwt)
end

--- Execute the script
-- @param conf kong configuration
function _M.execute(conf)
  add_jwt_header(conf)
end

return _M
```

Feel free to diff it and see the differences, the last bit I am unsure of is the best way to do the users id, I am not sure if sub is more appropriate or something like userid to pair with the username claim. I worry some may confuse what sub actually is without a more direct key value in the claim. Also the JWT isn't intended to be consumer centric really, its to validate the tx came from Stargate which is another reason idk if sub is an appropriate claim for the users id.

**Comment by brianwyka** [comment]
@jeremyjpj0916, according to https://tools.ietf.org/html/rfc7519#section-4.1.2, `sub` should be unique per issuer, or even globally.  Do you see it more accurate to send this as the consumer username in that case then, since it should be the principal?  If that's the case.  Maybe we then send `cid` as consumer id.

**Comment by jeremyjpj0916** [comment]
Why don't we just keep it simple and make claims that make sense to those unfamiliar with optional jwt standards(which are totally optional per RFC anyways and just intended as a basis on how a jwt might look)?

payload.consumerid
payload.consumername

or  
payload.userid
payload.username

? I rather not obfuscate the claim key from what it really represents, if I was as jwt newb and stargate newb the sub / cid and all that does not instantly click for me, I think its better to make human sense, even if we aren't using  a "standard" jwt claim key.

The issuer and audience fields all seem fine though and generally make sense to me. @rsbrisci your thoughts on how to present the consumer id / username in the jwt as well?

**Comment by brianwyka** [comment]
@jeremyjpj0916 I kept the name short based off the docs here:
https://tools.ietf.org/html/rfc7519#section-4.1

> All the names are short because a core goal of JWTs is for the representation to be compact.

**Comment by jeremyjpj0916** [comment]
In that case maybe cid = consumer id, and cun = consumer username ? Thing is we have a UUID header called optum-ext-cid which is a unique transaction id so that sort of clashes with having a "cid" claim being the consumer id in a way... the claim names themselves are aesthetic anyways. Will have to think on this a little so we pick this right and no one has any regrets cause we likely won't revisit this .

**Comment by brianwyka** [comment]
@jeremyjpj0916 let me know when you guys come to a consensus.

**Comment by jeremyjpj0916** [comment]
@brianwyka will do, waiting to get a chance to have some internal discussion on what we want for consumer name/id in the jwt as a final go ahead.

**Comment by jeremyjpj0916** [comment]
We have another meeting setup this week to try and finalize what we want for consumer name/id fields in claims.

**Comment by brianwyka** [comment]
Thanks for the update @jeremyjpj0916

**Comment by jeremyjpj0916** [comment]
@brianwyka 

Had a meeting among myself/Ross/Korver today. It was agreed that they wanted:

payload.consumerid
payload.consumername

As the final choice, can you adjust the code so we can wrap up final review and prep this for nonprod release?

**Comment by brianwyka** [comment]
@jeremyjpj0916 what about the `sub` field?

**Comment by fvnkerk** [comment]
Would it be possible to replace the values in authorisation header with the new token?

**Comment by brianwyka** [comment]
@fvnkerk, can you elaborate on what you mean here?

**Comment by fvnkerk** [comment]
Currently the only options to set the jwt token is either a header named JWT or a param in the url. It would be great if the authorisation header can also be used, e.g. 

Authorization: Bearer ${signed token}

This tends to be the default header/location used by by security frameworks used by developers of upstream systems, e.g. spring

**Comment by brianwyka** [comment]
@fvnkerk, probably best to solve that in a separate change.  Can you open up an issue to track?

**Comment by fvnkerk** [comment]
Thanks, will do.

**Comment by brianwyka** [comment]
@rsbrisci @jeremyjpj0916 ready for final review and approval.

**Review by jeremyjpj0916 — APPROVED** [review]
lgtm

**Comment by jeremyjpj0916** [comment]
@brianwyka rolling this out to stage first, will place into prod in a week or two.

**Pull request merged**
